//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IAccountDatabase.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.android5777_9254_6826.model.datasource;


import java.util.ArrayList;

import project.android.com.android5777_9254_6826.model.entities.Account;

public interface IAccountDatabase extends IDatabase {
	/**
	 *
	 * @param UserName
	 * @param Password
     * @return true - if succeeded , else false;
     */
	boolean addNewAccount(String UserName, String Password);
	ArrayList<Account> getAccountList();
	Account getAccount(long id) throws Exception;
	Account getAccount(String username) throws Exception;
	boolean isRegistered(String userName);

	/**
	 * checks if the account exists and returns true if the passToCheck equals to the Account's password
	 * if the account doesnt exists throws exception.
	 * @param userName hello
	 * @param passToCheck
	 * @return true if the passtoCheck equals to the account's password
	 * @throws Exception if the account was not found.
     */
	boolean verifyPassword(String userName,String passToCheck) throws Exception;
	int removeAccount(String username);
}
