//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IAttractionDatabase.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.android5777_9254_6826.model.datasource;


import java.util.ArrayList;
import java.util.Date;

import project.android.com.android5777_9254_6826.model.entities.Attraction;
import project.android.com.android5777_9254_6826.model.entities.Properties;

public interface IAttractionDatabase extends IDatabase {
    /**
     *
     * @param Type
     * @param Country
     * @param StartDate
     * @param EndDate
     * @param Price
     * @param Description
     * @param BusinessID
     * @return returns true if succeeded , else false;
     */
	public boolean addNewAttraction(Properties.AttractionType Type, String Country, Date StartDate,
								 Date EndDate, float Price, String Description, String BusinessID);

    /**
     *
     * @return list of the attraction in the database
     */
	public ArrayList<Attraction> getAttractionList();
}
