//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IBusinessDatabase.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.android5777_9254_6826.model.datasource;


import android.content.ContentValues;
import android.database.Cursor;
import android.net.Uri;

import java.net.URL;
import java.util.ArrayList;

import project.android.com.android5777_9254_6826.model.entities.Account;
import project.android.com.android5777_9254_6826.model.entities.Address;
import project.android.com.android5777_9254_6826.model.entities.Business;

public interface IBusinessDatabase extends IDatabase {
	int addNewBusiness(String ID, String Name, Address address, String Email, URL Website);
	int addNewBusiness(Business toInsert);
	ArrayList<Business> getBusinessList();
	boolean ifNewBusinessAdded();
	int removeBusiness(String businessID);
	int removeBusiness(int rowID);
	Uri insert(Business ac);
	int delete(Uri uri, String selection, String[] selectionArgs);
	int update(Uri uri, ContentValues values, String selection,
			   String[] selectionArgs);
	Cursor query(Uri uri, String[] projection, String selection,
				 String[] selectionArgs, String sortOrder);
}
