//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IBusinessDatabase.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.android5777_9254_6826.model.datasource;


import java.net.URL;
import java.util.ArrayList;

import project.android.com.android5777_9254_6826.model.entities.Address;
import project.android.com.android5777_9254_6826.model.entities.Business;

public interface IBusinessDatabase extends IDatabase {
	public boolean addNewBusiness(String ID, String Name, Address address, String Email, URL Website);
	public ArrayList<Business> getBusinessList();
}
