package project.android.com.android5777_9254_6826.model.datasource;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDatabase.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//




public interface IDatabase {
}
