//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.android5777_9254_6826.model.entities;



public class Account {
	 public long AccountNumber;
	 public String UserName;
	 public String Password;

	public Account(long id, String userName, String password) {
		this.AccountNumber = id;
		this.UserName = userName;
		this.Password = password;
	}
}
