//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Address.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.android5777_9254_6826.model.entities;


import java.io.Serializable;

public class Address implements Serializable {
	public Address(String country, String city, String street) {
		Country = country;
		City = city;
		Street = street;
	}
	public Address()
	{
		Country ="";
		City = "";
		Street ="";
	}

	private String Country;
	private String City;
	private String Street;

	public String getCountry() {
		return Country;
	}

	public void setCountry(String country) {
		Country = country;
	}

	public String getCity() {
		return City;
	}

	public void setCity(String city) {
		City = city;
	}

	public String getStreet() {
		return Street;
	}

	public void setStreet(String street) {
		Street = street;
	}

	@Override
	public String toString(){
		String toReturn  = "";
		toReturn+=Street+", ";
		toReturn+=City+", ";
		toReturn+=Country+".";
		return toReturn;

	}


}
