//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Attraction.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.android5777_9254_6826.model.entities;
import java.io.Serializable;
import java.util.Date;

import project.android.com.android5777_9254_6826.model.entities.Properties;


public class Attraction implements Serializable {
	private Properties.AttractionType Type;
	private String Country;
	private String StartDate;
	private String EndDate;
	private float Price;
	private String Description;
	private String BusinessID;
	private String AttractionID;



	private String AttractionName;

	public Attraction(String attractionID,Properties.AttractionType type,String attractionName,  String country, String startDate, String endDate, float price, String description, String businessID) {
		AttractionName= attractionName;
		Type = type;
		Country = country;
		StartDate = startDate;
		EndDate = endDate;
		Price = price;
		Description = description;
		BusinessID = businessID;
		AttractionID = attractionID;
	}

	public String getAttractionName() {
		return AttractionName;
	}

	public void setAttractionName(String attractionName) {
		AttractionName = attractionName;
	}
	public Properties.AttractionType getType() {
		return Type;
	}

	public void setType(Properties.AttractionType type) {
		Type = type;
	}

	public String getCountry() {
		return Country;
	}

	public void setCountry(String country) {
		Country = country;
	}

	public String getStartDate() {
		return StartDate;
	}

	public void setStartDate(String startDate) {
		StartDate = startDate;
	}

	public String getEndDate() {
		return EndDate;
	}

	public void setEndDate(String endDate) {
		EndDate = endDate;
	}

	public float getPrice() {
		return Price;
	}

	public void setPrice(float price) {
		Price = price;
	}

	public String getDescription() {
		return Description;
	}

	public void setDescription(String description) {
		Description = description;
	}

	public String getBusinessID() {
		return BusinessID;
	}

	public void setBusinessID(String businessID) {
		BusinessID = businessID;
	}

	public String getAttractionID() {
		return AttractionID;
	}

	public void setAttractionID(String attractionID) {
		AttractionID = attractionID;
	}
}
