//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Attraction.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.android5777_9254_6826.model.entities;
import java.util.Date;

import project.android.com.android5777_9254_6826.model.entities.Properties;


public class Attraction {
	public Properties.AttractionType Type;
	public String Country;
	public Date StartDate;
	public Date EndDate;
	public float Price;
	public String Description;
	public String BusinessID;

	public Attraction(Properties.AttractionType type, String country, Date startDate, Date endDate, float price, String description, String businessID) {
		Type = type;
		Country = country;
		StartDate = startDate;
		EndDate = endDate;
		Price = price;
		Description = description;
		BusinessID = businessID;
	}
}
