//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Business.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//

package project.android.com.android5777_9254_6826.model.entities;


import java.net.URL;

public class Business {
	private String BusinessID;
	private String BusinessName;
	private Address BusinessAddress;
	public String Email;
	public URL Website;

	public Business(String id, String name, Address address, String email, URL website) {
		BusinessID = id;
		BusinessName = name;
		BusinessAddress = address;
		Email = email;
		Website = website;
	}
}
