//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Properties.java
//  @ Date : 2016-11-21
//  @ Author : 
//
//
package project.android.com.android5777_9254_6826.model.entities;


import java.io.Serializable;

public class Properties implements Serializable {
	public static enum AttractionType {
		HotelDeal,
		TravelAgency,
		EntertainmentShow,
		Airline
	}
}
